# Generated by Django 2.0 on 2017-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='introduction',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
