# Generated by Django 2.0 on 2017-12-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0002_articles_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
