# Generated by Django 2.0 on 2017-12-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0003_auto_20171231_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-id']},
        ),
    ]
