# Generated by Django 2.0 on 2018-01-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0004_auto_20171231_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('cover', models.FileField(null=True, upload_to='cover_image')),
                ('page_view', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Article_Main_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_main_category', models.CharField(choices=[('fuxi', '祓禊'), ('yunji', '云笈'), ('saibo', '赛博')], max_length=16)),
                ('main_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_main_category', to='buboshe_app.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Articles_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_sub_category', models.CharField(choices=[('wuxian', '武侠'), ('xianxia', '仙侠'), ('xuanhuan', '玄幻'), ('yunjiqiqian', '云笈七签'), ('xuanhuan', '浴乎沂'), ('fenghuwuyu', '风乎舞雩'), ('yongergui', '咏而归'), ('chunqiuerxi', '春秋二禊'), ('kehuan', '科幻'), ('qihuan', '奇幻'), ('mohuan', '魔幻'), ('lapusaibo', '拉普赛博')], max_length=16)),
                ('sub_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sub_category', to='buboshe_app.Article')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
