# Generated by Django 2.0 on 2018-01-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0005_auto_20180104_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles_Sub_Category',
            new_name='Article_Sub_Category',
        ),
    ]
