# Generated by Django 2.0 on 2018-01-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buboshe_app', '0007_auto_20180104_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to='profile_image')),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article_main_category',
            name='main_article',
        ),
        migrations.RemoveField(
            model_name='article_sub_category',
            name='sub_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='page_view',
        ),
        migrations.AddField(
            model_name='article',
            name='createtime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='buboshe_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_category',
            field=models.CharField(choices=[('fuxi', '祓禊'), ('yunji', '云笈'), ('saibo', '赛博')], max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.CharField(choices=[('wuxian', '武侠'), ('xianxia', '仙侠'), ('xuanhuan', '玄幻'), ('yunjiqiqian', '云笈七签'), ('xuanhuan', '浴乎沂'), ('fenghuwuyu', '风乎舞雩'), ('yongergui', '咏而归'), ('chunqiuerxi', '春秋二禊'), ('kehuan', '科幻'), ('qihuan', '奇幻'), ('mohuan', '魔幻'), ('lapusaibo', '拉普赛博')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Article_Main_Category',
        ),
        migrations.DeleteModel(
            name='Article_Sub_Category',
        ),
    ]
