# Generated by Django 2.0 on 2018-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buboshe_app', '0008_auto_20180104_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[('hedongjun', '河东君'), ('lorelei', 'Lorelei'), ('jikegongdongdui', '鸡壳攻动队')], max_length=32),
        ),
    ]
